### ISSUE TITLE
npm run deploy - Issue

### ISSUE THREAD

**Issue by cristobalchao** [eXaminator/angular-es6-boilerplate#1]
I'm trying to use this boilerplate, it looks neat. However I'm running into some issues while deploying. 

I'm using the latest stable versions of npm (v3.5.2) and nodejs (v5.2.0)

Log:
```
$ npm run deploy

> angular-material-base@1.0.0 deploy /Users/.../..../...
> npm run build && firebase deploy


> angular-material-base@1.0.0 build /Users/.../..../...
> rm -rf build/* && webpack --config webpack.prod.config.js --progress

 26% 44/161 build modulesModuleBuildError: Module build failed: TypeError: config.formatter is not a function
    at lint (/Users/.../..../.../node_modules/eslint-loader/index.js:59:29)
    at Object.module.exports (/Users/.../..../.../node_modules/eslint-loader/index.js:127:7)
    at DependenciesBlock.onModuleBuildFailed (/Users/.../..../.../node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/.../..../.../node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /User/.../..../.../node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/.../..../.../node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.module.exports (/Users/.../..../.../node_modules/eslint-loader/index.js:130:7)
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/.../..../.../node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/Users/.../..../.../node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/Users/.../..../.../node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/.../..../.../node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/.../..../.../node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/.../..../.../node_modules/graceful-fs/graceful-fs.js:76:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:405:3)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! angular-material-base@1.0.0 build: `rm -rf build/* && webpack --config webpack.prod.config.js --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-material-base@1.0.0 build script 'rm -rf build/* && webpack --config webpack.prod.config.js --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-material-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf build/* && webpack --config webpack.prod.config.js --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-material-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-material-base
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/.../..../.../npm-debug.log

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! angular-material-base@1.0.0 deploy: `npm run build && firebase deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-material-base@1.0.0 deploy script 'npm run build && firebase deploy'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-material-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && firebase deploy
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-material-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-material-base
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/.../..../.../npm-debug.log
```

**Comment by eXaminator** [comment]
Uh, I didn't expect anyone besides me using this :D

I'll have a look at it tonight after work. I have a pretty good idea where to look.

**Comment by cristobalchao** [comment]
Thanks Steven for your prompt answer! I would like to use this boilerplate
more extensively, it works great except when I want to build/deploy the
app. :)

**Comment by eXaminator** [comment]
It should now work as expected :)

One thing to note: HTML Files won't be minimized now as that seems to produce strange errors. But IMHO that's not really important anyway :)

**Comment by cristobalchao** [comment]
Now works like a charm! Thanks Steven!! :)

**Comment by eXaminator** [comment]
You're welcome!
